levi9_sport:
    resource: "@Levi9SportBundle/Controller/"
    type:     annotation
    prefix:     /{_locale}
    defaults: { _locale : en }
    requirements:
        _locale: en|ru
logout:
    path:   /logout

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: login_route
        permanent: true