levi9_sport:
    resource: "@Levi9SportBundle/Controller/"
    type:     annotation
    prefix:     /{_locale}
    defaults: { _locale : en }
    requirements:
        _locale: en|ru
logout:
    path:   /logout