security:
    encoders:
        Levi9\SportBundle\Entity\User: plaintext

    providers:
        db_provider:
            entity:
                class: Levi9SportBundle:User
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: login_route
                check_path: login_check
            logout:
                path: logout
                target: login_route

    access_control:
        - { path: ^/(en|ru)/login?, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|ru)/exercises, roles: ROLE_USER }